"""
File: core_sql_anonymizer.py
Description: Provides the foundational logic for SQL query anonymization utilizing a deterministic pseudonymization protocol.
             This module systematically masks string/numeric literals and hashes identifiers (e.g., table and column names)
             to prevent data leakage, while preserving the grammatical structure of the original SQL statements.
"""

import re
import hashlib


class CoreSQLAnonymizer:
    """
    Core module for SQL query anonymization.
    Implements the deterministic pseudonymization protocol.
    Operates independently of hard-coded dictionaries to accommodate arbitrary database schemas.
    """

    def __init__(self, mask_literals=True):
        self.mask_literals = mask_literals
        # Standard SQL keywords (preserves grammatical structure during anonymization)
        self.sql_keywords = {
            "SELECT", "FROM", "WHERE", "AND", "OR", "IN", "IS", "NOT", "NULL",
            "ORDER", "BY", "GROUP", "LIMIT", "UPDATE", "SET", "DELETE", "INSERT",
            "INTO", "VALUES", "AS", "ON", "JOIN", "INNER", "LEFT", "RIGHT",
            "OUTER", "FULL", "HAVING", "ASC", "DESC", "BETWEEN", "LIKE", "DROP",
            "TRUNCATE", "ALTER", "GRANT", "REVOKE", "CREATE", "TABLE", "INDEX",
            "EXISTS", "COUNT", "MAX", "MIN", "SUM", "AVG", "CAST", "CONVERT",
        }
        # Cache mechanism to accelerate the hashing process and ensure deterministic behavior
        self._hash_cache = {}

    def _hash_identifier(self, identifier):
        """
        Transforms database identifiers (e.g., table names, column names) into cryptographic hashes.
        """
        identifier_lower = identifier.lower()

        if identifier_lower not in self._hash_cache:
            # Extracting the first 8 characters of the SHA-256 digest provides a sufficient security margin while maintaining readability
            hashed = hashlib.sha256(identifier_lower.encode("utf-8")).hexdigest()[:8]
            self._hash_cache[identifier_lower] = f"id_{hashed}"

        return self._hash_cache[identifier_lower]

    def anonymize_sql(self, sql_text):
        """
        Main function: Accepts an original SQL query string and returns its anonymized counterpart.
        """
        if not isinstance(sql_text, str) or not sql_text.strip():
            return str(sql_text)

        anonymized = sql_text

        # 1. LITERAL MASKING (Value Obfuscation)
        if self.mask_literals:
            anonymized = re.sub(r"'[^']*'", "'<STR>'", anonymized)
            anonymized = re.sub(r'"[^"]*"', '"<STR>"', anonymized)
            anonymized = re.sub(r"\b\d+\.?\d*\b", "<NUM>", anonymized)

        # 2. IDENTIFIER HASHING (Structural Encryption)
        def replace_word(match):
            word = match.group(0)
            
            # [FIXED BUG]: Protect placeholders to prevent them from being erroneously hashed as identifiers
            if word in ["NUM", "STR"]:
                return word
                
            if word.upper() in self.sql_keywords:
                return word.upper()
            else:
                return self._hash_identifier(word)

        anonymized = re.sub(r"\b[A-Za-z_][A-Za-z0-9_]*\b", replace_word, anonymized)

        # Eliminate extraneous whitespaces generated by regular expression substitutions (if any)
        anonymized = re.sub(r"\s{2,}", " ", anonymized).strip()

        return anonymized


# =====================================================================
# QUICK MODULE TESTING UPON DIRECT EXECUTION
# =====================================================================
if __name__ == "__main__":
    anonymizer = CoreSQLAnonymizer()
    sample_sql = "SELECT * FROM users WHERE 1 = 1 OR age > 25"

    print("--- CORE MODULE TEST EXECUTION ---")
    print(f"ORIGINAL   : {sample_sql}")
    print(f"ANONYMIZED : {anonymizer.anonymize_sql(sample_sql)}")
    # Expected output: SELECT * FROM id_... WHERE <NUM> = <NUM> OR id_... > <NUM>